### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by Killer-Kat** [Nick-Stewart7/The-Gungeon-Helper#1]
I am interested to see what this code does but I cant figure out how to get it working. Could you provide a description of what the code does?

**Comment by Nick-Stewart7** [comment]
Hello Friend! I am glad to see that you are interested in this project. I unfortunately did not fully fledged this thing out however, this code does do something. Currently this code scrapes the gungeon wiki with beautiful soup 4 and puts the data into a data structure. The data is currently just the guns in the game and their stats.I really want to spend more time on this and get it working completely but school is getting in my way. My goal was to have it as a tool that you can add items to and do calculations to see what your synergies are (since you cant see them) and how over-powered you are. Try taking the gunsoup and import comments out and then install beautiful soup4 on your machine. The code should run then. Let me know what happens-Nick Stewart Sent from Mail for Windows 10 From: Killer-KatSent: Thursday, November 5, 2020 7:46 PMTo: Nick-Stewart7/The-Gungeon-HelperCc: SubscribedSubject: [Nick-Stewart7/The-Gungeon-Helper] How does this work? (#1) I am interested to see what this code does but I cant figure out how to get it working. Could you provide a description of what the code does?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Killer-Kat** [comment]
Cool I wish you luck! I had some similar ideas for apps to make but alas I also need to focus on studying. I'm certainly interested what you come up with in the future and perhaps once I am more experienced we could collaborate.

**Comment by Nick-Stewart7** [comment]
Yeah im starting to learn a better way to do this project so I will try to keep you updated Sent from Mail for Windows 10 From: Killer-KatSent: Monday, November 9, 2020 12:09 AMTo: Nick-Stewart7/The-Gungeon-HelperCc: Nick-Stewart7; CommentSubject: Re: [Nick-Stewart7/The-Gungeon-Helper] How does this work? (#1) Cool I wish you luck! I had some similar ideas for apps to make but alas I also need to focus on studying. I'm certainly interested what you come up with in the future and perhaps once I am more experienced we could collaborate.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
